### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by nenkoru** [BlinkDL/ChatRWKV#78]
Encountering an issue with setting `RWKV_CUDA_ON` to '1'  when using multi-gpu strategy.
All the GPUs are the same 3060ti 8Gb with cuda 11.7 installed.

```
(base) [rig-nenkoru@localhost Raven-RWKV-7B]$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
```
torch
ninja
tokenizers
rwkv==0.6.2
pynvml
huggingface_hub
gradio>=3.17.1
```
```
(llama) [rig-nenkoru@localhost rwkv]$ pip show torch
Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
```
```
'cuda:0 fp16 -> cuda:1 fp16 -> cuda:2 fp16'
```
```
Traceback (most recent call last):
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/gradio/interface.py", line 621, in fn
    for output in self.fn(*args):
  File "/home/rig-nenkoru/Raven-RWKV-7B/./app.py", line 66, in evaluate
    out, state = model.forward(pipeline.encode(ctx)[-ctx_limit:] if i == 0 else [token], state)
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/rwkv/model.py", line 573, in forward
    x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/rig-nenkoru/miniconda3/envs/llama/lib/python3.10/site-packages/rwkv/model.py", line 485, in cuda_att_seq
            y, aa, bb, pp = cuda_wkv(T, C, t_decay, t_first, k, v, aa, bb, pp)
            
            out = (r * y) @ ow
                   ~~~~~ <--- HERE
            return x + out, xx[-1,:], aa, bb, pp
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by nenkoru** [comment]
The same issue were reported in https://github.com/BlinkDL/ChatRWKV/issues/38#issuecomment-1474838756 by @burgerlawful

**Comment by BlinkDL** [comment]
@nenkoru pls try latest ChatRWKV & rwkv 0.7.3
should be fixed now

**Comment by nenkoru** [comment]
Yeah, it works now. But I don't see any noticebale difference between turning this feature on or off. Here are timings per .forward call. However, I noticed slightly less memory usage of around 1.5 - 2GB for 14B model so I managed to fit a little more layers without quantization into i8. It's also worth mentioning that the CPU on the machine fairly slow - AMD Athlon 3000G with 2 cores(4 threads) that could be the bottleneck in my case.

---
Cuda optimization OFF. 7B
cuda:0 fp16 -> cuda:1 fp16 -> cuda:2 fp16
```
forward time: 0.023224592208862305
forward time: 0.02307891845703125
forward time: 0.023171663284301758
forward time: 0.023991107940673828
```

Cuda optimization ON. 7B
cuda:0 fp16 -> cuda:1 fp16 -> cuda:2 fp16
```
forward time: 0.023212432861328125
forward time: 0.021632671356201172
forward time: 0.021616697311401367
forward time: 0.022366046905517578
```

---
Cuda optimization ON. 14B.
cuda:0 fp16 *10 -> cuda:1 fp16 *10 -> cuda:2 fp16 *10 -> cuda:3 fp16 *10 -> cuda:3 fp16i8
```
forward time: 0.02741098403930664
forward time: 0.030609130859375
forward time: 0.029874563217163086
forward time: 0.02969217300415039
forward time: 0.028966665267944336
forward time: 0.030252695083618164
```

Cuda optimization OFF. 14B.
cuda:0 fp16 *10 -> cuda:1 fp16 *10 -> cuda:2 fp16 *10 -> cuda:3 fp16 *7 -> cuda:3 fp16i8
```
forward time: 0.029529571533203125
forward time: 0.030321836471557617
forward time: 0.02967238426208496
forward time: 0.030389785766601562
forward time: 0.03206944465637207
forward time: 0.030094385147094727
```

**Comment by BlinkDL** [comment]
@nenkoru It's 10x faster for long inputs
